version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: docker build -t jamcswain/gitreview-gitserver .
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push
          command: docker push jamcswain/gitreview-gitserver

  deploy:
    docker:
      - image: alpine
    steps:
      - run:
          name: Install SSH
          command: apk add --no-cache openssh
      - add_ssh_keys:
          fingerprints:
            - "21:c9:6c:11:26:91:eb:bb:76:c7:20:de:5f:82:c2:44"
      - run:
          name: Add known_hosts
          command: echo "$SSH_HOSTNAME,$SSH_IP $SSH_SCHEME $SSH_SERVER_KEY" >> ~/.ssh/known_hosts
      - run:
          name: Pull Docker images
          command: ssh $SSH_USERNAME@$SSH_HOSTNAME docker-compose -f gitreview/docker-compose.yml pull
      - run:
          name: Bring docker-compose up
          command: ssh $SSH_USERNAME@$SSH_HOSTNAME docker-compose -f gitreview/docker-compose.yml up -d

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master